services:
  web:
    image: asia-south1-docker.pkg.dev/whizhack-vl-438009/docker-images-for-scenarios/thedigitalheist:web-03-safehouse-v1
    environment:
      PORT: ${PORT}
      SESSION_SECRET: ${SESSION_SECRET}
      FLAG: ${FLAG}
      INTERNAL_TOKEN: ${INTERNAL_TOKEN}
    ports:
      - "5003:${PORT}"
    depends_on:
      - internal-admin

  internal-admin:
    image: asia-south1-docker.pkg.dev/whizhack-vl-438009/docker-images-for-scenarios/thedigitalheist:web-03-internal-admin-v1
    environment:
      FLAG: ${FLAG}
      INTERNAL_TOKEN: ${INTERNAL_TOKEN}
    expose:
      - "8080"

