services:
  web:
    build: .
    environment:
      PORT: ${PORT:-5101}
      KEY: ${KEY:-RDxlT2USNk6yFo1Ejmenl1tkrJ4vGz9T2YKrqOQT}
      FLAG: ${FLAG:-TDHCTF{BELLA_CIAO_NO_MORE_DOT_DOT_SLASH}}
    ports:
      - "${PORT:-5101}:${PORT:-5101}"
    restart: unless-stopped
